### ISSUE TITLE
Separate `use_asyncio` and `use_smartnoise_sql`

### ISSUE THREAD

**Issue by mhauru** [alan-turing-institute/sqlsynthgen#118]
Currently we say `use_asyncio = not use_smartnoise_sql` but in reality these are separate concerns (with the limitation that we can't have both being `True` at the same time, because smartnoise-sql doesn't know how to handle an asyncio engine).

**Comment by Iain-S** [comment]
If you let me know when this is done, I shall update the loans tutorial to add src stats and forward to HSBC.

**Comment by mhauru** [comment]
Done. More edits to how make-stats works are coming though, see #123.
