### ISSUE TITLE
Publish SQLSynthGen on PyPI

### ISSUE THREAD

**Issue by Iain-S** [alan-turing-institute/sqlsynthgen#2]
Subissues of this big issue:
* https://github.com/alan-turing-institute/sqlsynthgen/issues/5
* https://github.com/alan-turing-institute/sqlsynthgen/issues/4
* https://github.com/alan-turing-institute/sqlsynthgen/issues/3
* https://github.com/alan-turing-institute/sqlsynthgen/issues/7
* https://github.com/alan-turing-institute/sqlsynthgen/issues/9
* https://github.com/alan-turing-institute/sqlsynthgen/issues/8

**Comment by mhauru** [comment]
Done
