### ISSUE TITLE
Document the config file format

### ISSUE THREAD

**Issue by Iain-S** [alan-turing-institute/sqlsynthgen#57]
We should provide an example config file (or point to the one used for testing). We could also define the format using a JSON schema and document it the way that, for example, GitHub does [here](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions).

**Comment by mhauru** [comment]
For the smartnoise-sql block we should just refer here: https://docs.smartnoise.org/sql/metadata.html

**Comment by Iain-S** [comment]
PR #91 defined the valid config schema using jsonschema and added a docs page. We might still want to

- [ ] refer to the smartnoise docs (linked above)
- [ ] explain what the blocks do in plain text

**Comment by mhauru** [comment]
I think this is done as of https://github.com/alan-turing-institute/sqlsynthgen/pull/136
