### ISSUE TITLE
Testing with star schema

### ISSUE THREAD

**Issue by myyong** [alan-turing-institute/sqlsynthgen#60]
Fails at `create-schema` step, for both postgres.star (generated from Satellite) and stars.star_080223 (generated from InformDB)

**Error for postgres.star**
The error when running on postgres.star is as follows:
> psycopg2.errors.UndefinedTable: relation "star.advance_decision_advance_decision_id_seq" does not exist
LINE 1: ...atetime, valid_from, stored_from) VALUES (nextval('"star.adv...

The table snippet for `postgres.star.advance_decision` is as follows:
```sql
CREATE TABLE IF NOT EXISTS star.advance_decision
(
    advance_decision_id integer NOT NULL DEFAULT nextval('star.advance_decision_advance_decision_id_seq'::regclass),
    advance_decision_type_id bigint,
```

**Error for stars.star_080223**
The error when running on stars.star_080223 is as follows:
>sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) null value in column "advance_decision_type_id" violates not-null constraint
DETAIL:  Failing row contains (null, Black, White).

The table snippet for `advance_decision_type_id` is as follows:
```sql
CREATE TABLE IF NOT EXISTS star_080223.advance_decision_type
(
    advance_decision_type_id bigint NOT NULL,
```

**Comment by Iain-S** [comment]
@myyong are you using the latest version of `main` and have you run `poetry install` recently? I think Markus and I fixed the issue you're having with `star_080223` a while back.

**Comment by Iain-S** [comment]
Closing as likely a red herring.
