### ISSUE TITLE
Document simple end-to-end use case for SSG

### ISSUE THREAD

**Issue by Iain-S** [alan-turing-institute/sqlsynthgen#61]
E.g. we could document the test case or a person - department - widget type scenario.

**Comment by Iain-S** [comment]
- [ ] *Iain* Compare with simple tutorial in other branch
- [ ] *May* Which branch?

**Comment by Iain-S** [comment]
I think https://github.com/alan-turing-institute/sqlsynthgen/pull/72 closes this.

**Comment by myyong** [comment]
@Iain-S We have this one: https://github.com/alan-turing-institute/sqlsynthgen/blob/29-document-end-to-end-use-case/docs/source/simple_example.rst

**Comment by Iain-S** [comment]
Closed by #72
