### ISSUE TITLE
Deal with null values in vocabulary tables

### ISSUE THREAD

**Issue by mhauru** [alan-turing-institute/sqlsynthgen#65]
We ran into a case where a null value in an integer table was recorded as `""` in the CSV file, which then generated a complaint about not being able to write a string into an integer column when doing `create-vocab`.

**Comment by Iain-S** [comment]
There might be a DictReader option for this.

**Comment by mhauru** [comment]
I think we may have to move away from CSV. Quoting the [docs](https://docs.python.org/3/library/csv.html#csv.writer):
>To make it as easy as possible to interface with modules which implement the DB API, the value [None](https://docs.python.org/3/library/constants.html#None) is written as the empty string. While this isn’t a reversible transformation, it makes it easier to dump SQL NULL data values to CSV files without preprocessing the data returned from a cursor.fetch* call. All other non-string data are stringified with [str()](https://docs.python.org/3/library/stdtypes.html#str) before being written.
