### ISSUE TITLE
Add option to overwrite `ssg.py` etc

### ISSUE THREAD

**Issue by mhauru** [alan-turing-institute/sqlsynthgen#66]
It's good that we are prudent in not overwriting files when e.g. making the generators or the CSV files, but it would also be good to have an option to do so. Today @myyong got into a loop of repeatedly running `rm ssg.py; rm *.csv; sqlsynthgen make-generators`, and we were left hoping for a `sqlsynthgen make-generators --overwrite` option. Should there be separate options for which files to overwrite?

**Comment by myyong** [comment]
Might be easier to do this via scripts. Let's chart our the user paths before we decide on this?

**Comment by Iain-S** [comment]
Would be good to add this `--overwrite` or `--force` option to `make-tables`, `make-generators` and `make-vocab`.

**Comment by mhauru** [comment]
`--force` and `-f` are probably indeed better than `--overwrite`, that's what users would expect it to be called.
