### ISSUE TITLE
Skip copying vocabulary tables if exists

### ISSUE THREAD

**Issue by myyong** [alan-turing-institute/sqlsynthgen#67]
@mhauru provided script so that we only load vocabulary tables if they are empty. Without this, we get the unique constraint error as the tables already contain vocab values.
            
```python
try:
   vocab_table.load(dst_conn)
   except sqlalchemy.exc.IntegrityError as e:
   logging.warn(f"Loading the vocabulary table {vocab_table.name} failed:")
   logging.warn(e)
```

This should go around line 45 in `create.py`

**Comment by mhauru** [comment]
Closed by #69, once it's merged
