### ISSUE TITLE
Document sqlsynthgen

### ISSUE THREAD

**Issue by Iain-S** [alan-turing-institute/sqlsynthgen#8]
## Minimum
 
- [ ] Examples in the README

## Desirable

- [x] Document the API with docstrings
- [x] Publish to readthedocs or github pages or similar

**Comment by myyong** [comment]
Draft documentation on readthedocs [here](https://sqlsynthgen.readthedocs.io/en/latest/sqlsynthgen.html), pushed from this [commit](https://github.com/alan-turing-institute/sqlsynthgen/commit/a7885f0f27ec3e4681423bc6ce10f9220772079a).

**Comment by myyong** [comment]
This issue will be closed when 

- [ ] pull requested into main
- [ ] readthedocs pulls from main
- [ ] pylint extension on adequate docstrings

**Comment by Iain-S** [comment]
I think there was one extra thing about Readthedocs access too.

- [ ] How can repo admins get access to readthedocs

**Comment by Iain-S** [comment]
All done 😄
