### ISSUE TITLE
Simplify config

### ISSUE THREAD

**Issue by Iain-S** [alan-turing-institute/sqlsynthgen#93]
A few things come to mind:

- args
   - [ ] the generator `args` is a dict where you have to specify the name(s) of the function arguments but what if the function only has positional arguments? For example, if it is declared as `def myfunc(*args)`.
   - [ ] why does `args` sometimes take `null`? Would it be better to simply leave it out if there are no args?
  - could we use `args: [1,2]` and `kwargs: {"a": 1, "b": 2}` to work around this?
- [ ] columns_assigned seems to take a string or a list of strings. Would it be better to only take the list of strings?
- [ ] simplify imports (see also #92)

**Comment by mhauru** [comment]
Agree on the first point, having `args` and `kwargs` would be good. I think story generators and row generators may also currently do this differently from each other, which is extra bad.

A bit ambivalent about the middle point. There's something very intuitive about single values vs singleton lists from a user experience point of view, but something confusing about mixing types (list vs string) from a logic, architecture, software point of view.

**Comment by mhauru** [comment]
Another point that bothers me a bit: Epsilon and delta have to be provided even when `use-smartnoise-sql: false`. This was the case already before the validation stuff, for some (ungood) reason I can't recall.

**Comment by cptanalatriste** [comment]
@Iain-S happy to work on that! I'll assign the issue to myself

**Comment by cptanalatriste** [comment]
A note here, now that `SSG` was released in the wild :) . If we implement handling `args` and `kwargs` as different generator properties supporting different types, we risk breaking the code that now uses `args` for providing keyword arguments.

For backward-compatibility reasons, shall just extend `args`, and made it support **both** a list of values (`[1, 2, 3]`) **and** objects (`{"a": 1, "b": 2, "c":3`)?

**Comment by mhauru** [comment]
With overwhelming probability SSG currently has no other users besides us, so I wouldn't worry about backwards compatibility. Even if we had some users, it's still a very early stage tool.

**Comment by cptanalatriste** [comment]
@mhauru, shall I implement the `args` and `kwargs` feature for story generators too?
